Feature/home apis text
mitl-feedmysheep/server pull request #20
Opened 2023-12-11 13:47 UTC by SantinoMin

feat : /app/text 텍스트 조회 부분 - 코드 작성 완료, 테스트 완료.
         (해당 내용: 스크린 키에 해당하는 텍스트를 가져옵니다.)
        
         * 절차
         1) fms-token 인증 토큰 필요 (회원가입 또는 로그인 시 발급)
         2) 스크린키에 해당하는 텍스트 조회 가능

2023-12-11 14:23 UTC, martin-dsp requested changes
굳~ 🙏

2023-12-11 15:39 UTC, SantinoMin commented on src/main/java/feedmysheep/feedmysheepapi/domain/text/app/repository/TextRepository.java
> +
@Repository바로 위에 
// TODO 테스트코드
명시 완료.

2023-12-11 15:43 UTC, SantinoMin commented on src/main/java/feedmysheep/feedmysheepapi/domain/text/app/repository/TextRepository.java
> +  List<TextEntity> getTextListByScreenKey(@Param("screenKey") String screenKey);
좋은 질문입니다.
리스트로 받아야 될 이유 없는 거 같아서, List<>부분 삭제하였습니다.
(swagger API SPEC에 보니, 리스트 형식으로 받는건 아닌걸로 확인됨.)

2023-12-12 06:56 UTC, SantinoMin commented on src/main/java/feedmysheep/feedmysheepapi/domain/text/app/repository/TextRepository.java
> +  List<TextEntity> getTextListByScreenKey(@Param("screenKey") String screenKey);
-> 리스트로 반환 할 이유 없다고 판단되어, 단수형으로  수정 완료.

2023-12-12 06:57 UTC, SantinoMin commented on src/main/java/feedmysheep/feedmysheepapi/domain/text/app/service/TextService.java
> +    TextEntity text = textList.get(0);
-> 복수형이라 생각해서, 텍스트 리스트 중에서 하나를 가져오다고 생각 했었는데, 
     단수형이라고 확인되어, 해당 코드는 삭제 하였습니다.

2023-12-13 23:35 UTC, martin-dsp commented on src/main/java/feedmysheep/feedmysheepapi/domain/media/app/dto/MediaMapper.java
> +//package feedmysheep.feedmysheepapi.domain.media.app.dto;
혹시 해당 파일 주석처리 된 이유가 있을까요???

2023-12-13 23:36 UTC, martin-dsp commented on src/main/java/feedmysheep/feedmysheepapi/domain/text/app/service/TextService.java
> +    if (text.getScreenKey() == null) {
이것도 체이닝으로 붙여주면 좋곘어요!
(사실 개인 스타일이라고 생각합니다만.. 지금 스타일 잡아가고 있으니까 통일해요!)

2023-12-13 23:36 UTC, martin-dsp requested changes
마지막!

2023-12-15 05:49 UTC, SantinoMin commented on src/main/java/feedmysheep/feedmysheepapi/domain/media/app/dto/MediaMapper.java
> +//package feedmysheep.feedmysheepapi.domain.media.app.dto;
@martin-dsp 
아마 수정하는 과정에서, 불필요한 import들 제거된 걸로 보입니다.
기존 코드에는 주석되어 있지 않습니다 :)

2023-12-15 06:15 UTC, SantinoMin commented on src/main/java/feedmysheep/feedmysheepapi/domain/text/app/service/TextService.java
> +    if (text.getScreenKey() == null) {
@martin-dsp return부분에서 getTextByScreenKey의 매개변수로 text변수가 필요한데,
                      ( return this.textMapper.getTextByScreenKey(text); )
                      위에 이야기 한 코드(28-31)부분을 어떤식으로 체이닝 할 수 있을까요?
                       예시로 보여주면, 다음번에 참고해서 진행 할게용.
                       
                      *예상되는 코드
                     return this.textMapper.getTextByScreenKey(
                                 this.textRepository.getTextByScreenKey(screenKey)
                                 );

                     위와 같이 이런식으로 만들어지는걸 말한걸까요?

2023-12-30 12:37 UTC, martin-dsp approved these changes

2023-12-30 12:45 UTC, merged